info:
  title: Salcedonie API
  version: 1.0.0
servers:
  - url: 'https://api.salcedonie.nakasar.me'
  - url: 'http://localhost:5000'
openapi: 3.0.0
apis:
  - ./src/**/*.js
paths:
  /auth:
    post:
      operationId: auth
      summary: Auth endpoint to generate a token.
      description: Authenticate against username and password to retrieve an access token.
      requestBody:
        description: User credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
              example:
                username: John Smith
                password: Jo0hnPAs0rdN0tS3cur3
      responses:
        '200':
          description: User access token.
          content:
            application/json:
              schema:
                type: string
  /users:
    get:
      operationId: getUsers
      summary: Get existing users
      description: Get existing users summaries.
      security:
        - admin: []
      responses:
        '200':
          description: List of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      operationId: createUser
      summary: Create a user
      description: Create a user
      security:
        - admin: []
      requestBody:
        description: User to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User created (see id in Location header)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  '/users/{userId}':
    post:
      operationId: updateUser
      summary: Update a user
      description: Update a user
      security:
        - admin: []
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        description: Fields to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '204':
          description: User updated
components:
  schemas:
    UserCreate:
      type: object
      properties:
        username:
          type: string
        discord_id:
          type: string
        admin:
          type: boolean
      example:
        username: john Smith
        discord_id: 11119836820
        admin: false
    User:
      allOf:
        - $ref: '#/components/schemas/UserCreate'
        - type: object
          properties:
            id:
              type: string
          example:
            id: 5c1c06cd8d93224570fcc65b
  securitySchemes:
    admin:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    userId:
      name: userId
      in: path
      required: true
      description: ID of user
      schema:
        type: string
        example: 5c1c06cd8d93224570fcc65b
tags: []
